---
# search installed and running dockers
- name: Check
  ansible.builtin.include_tasks: check.yml
  tags: 
    - always
 
# install docker composes
- name: Install missing docker composes
  ansible.builtin.include_tasks: install.yml
  loop: "{{ docker_services | dict2items }}"
  tags:
    - install

# update images and restart docker composes
- name: Update and restart docker composes
  ansible.builtin.include_tasks: update.yml
  loop: "{{ docker_services | dict2items }}"
  tags:
    - update
    - pull
    - never

# Start/Stop docker composes
- name: Start/Stop docker composes
  ansible.builtin.include_tasks: manage.yml
  loop: "{{ docker_services | dict2items }}"
  tags:
    - start
    - stop
    - restart
    - down
    - disable
    - never